general:
  id: isvd-proxy
  ports:
    ldap: 0
    ldaps: {{ .Values.services.isvdproxy.ports.ldapsproxy }}
  license:
  admin:
    dn: "secret:isvdcred/admindn"
    pwd: "secret:isvdcred/adminpwd"
  ssl:
    fips: {{ .Values.fips }}
    protocols:
      - "TLS12"
      - "TLS13"
    cert-label: "isvgim"
  audit:
    enabled: {{ .Values.services.isvdproxy.auditlog }}
  key-stash: B64:GAAAAHM1Q2lqMCtLYVppZUhOemprZi9XSGc9PThOcHIiXmA9RlB0Rji/nsd3MpTYvRzUn5joE804v57HdzKU2L0c1J+Y6BPNnceUEUr3I0I4v57HdzKU2L0c1J+Y6BPNnceUEUr3I0I/+VsYL0fIEQ==

proxy:
  suffixes:
  - name: "isvgim"
    num-partitions: 1
    base: {{ .Values.services.isvd.rootSuffix | quote }}
    high-consistency: true
    servers:
      - name: "isvd-replica-1"
        role: "primarywrite"
        index: 1
      - name: "isvd-replica-2"
        role: "primarywrite"
        index: 1
  - name: "ibmpolicies"
    num-partitions: 1
    base: "cn=ibmpolicies"
    high-consistency: true
    servers:
      - name: "isvd-replica-1"
        role: "primarywrite"
        index: 1
      - name: "isvd-replica-2"
        role: "primarywrite"
        index: 1

  server-groups:
  - name: "group_a"
    servers:
    - name: "isvd-replica-1"
      id: "isvd-replica-1"
      target: "ldaps://isvd-replica-1:{{ .Values.services.isvd.ports.ldaps }}"
      bind-method: "Simple"
      user:
        dn: "secret:isvdcred/admindn"
        password: "secret:isvdcred/adminpwd"
    - name: "isvd-replica-2"
      id: "isvd-replica-2"
      target: "ldaps://isvd-replica-2:{{ .Values.services.isvd.ports.ldaps }}"
      bind-method: "Simple"
      user:
        dn: "secret:isvdcred/admindn"
        password: "secret:isvdcred/adminpwd"

keyfile:
  keys:
  - key: "@/var/isvd/config/proxy.pem"
    label: "isvgim"
  trusted-certificates:
  - "@/var/isvd/config/isvgimRootCA.crt"
