apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    kubernetes.io/metadata.name: {{ .Values.namespace }}
    pod-security-kubernetes.io/enforce: baseline
    pod-security-kubernetes.io/enforce-version: v1.26
    pod-security-kubernetes.io/warn: baseline
    pod-security-kubernetes.io/warn-version: latest
