apiVersion: v1
kind: ServiceAccount
metadata:
  name: isvd
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: isvd-role
  namespace: {{ .Values.namespace }}
rules:
- resources: [ "secrets" ]
  verbs: [ "get", "list", "watch" ]
  apiGroups: [ "" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: isvd-role-bind
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: isvd
  apiGroup: ""
roleRef:
  kind: Role
  name: isvd-role
  apiGroup: ""

