apiVersion: v1
kind: Service
metadata:
  name: isvd-replica-2
  namespace: {{ .Values.namespace }}
  labels:
    app: isvd-server
spec:
  selector:
    app: isvd-replica-2
  ports:
    - name: isvd-replica-2-ldaps
      port: {{ .Values.services.isvd.ports.ldaps }}
      protocol: TCP
