apiVersion: v1
kind: Service
metadata:
  name: mq-headless
  namespace: {{ .Values.namespace }}
  labels:
    app: isvgim
spec:
  clusterIP: None
  selector:
    app: isvgim
  ports:
    - name: mq
      port: {{ .Values.services.mqlocal.ports.mq }}
    - name: console
      port: {{ .Values.services.mqlocal.ports.console }}

