apiVersion: apps/v1
kind: Deployment
metadata:
  name: isvd-replica-1
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: isvd-replica-1
  template: 
    metadata:
      labels:
        app: isvd-replica-1
    spec:
      # The name of the service account which has the required
      # capabilities enabled for the isvd container.
      serviceAccountName: isvd

      {{ if not .Values.isOpenShift}}# User and group information for the container.
      securityContext:
        runAsUser: {{ .Values.services.isvd.user }}
        fsGroup: {{ .Values.services.isvd.group }}{{end}}

      # We use a volume to store the configuration for the 
      # environment.
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: {{ .Values.services.isvd.pgSharedMemory | quote }}
      - name: config-volume
        configMap:
          name: isvgimldap
      - name: data-volume 
        persistentVolumeClaim: 
          claimName: replica-1-pvc

      imagePullSecrets:
      - name: regcred

      containers:
      - name: isvd-replica
        
        # The fully qualified name of the image.
        image: {{ .Values.images.isvd }}
        imagePullPolicy: IfNotPresent

        # The port on which the container will be listening.
        ports:
        - containerPort: {{ .Values.services.isvd.ports.ldaps }}

        # Environment definition.
        env:
        - name: YAML_CONFIG_FILE
          value: /var/isvd/config/ldap_config.yaml
        - name: TZ
          value: ":{{ .Values.timezone }}"
          
        # The configuration volume.
        volumeMounts:
        - name: config-volume
          mountPath: /var/isvd/config
        - name: data-volume
          mountPath: /var/isvd/data
        - name: dshm
          mountPath: /dev/shm

        # The liveness, readiness and startup probes are used by
        # Kubernetes to monitor the health of the container.  Our 
        # health is governed by the health_check.sh script which is
        # provided by the container.
        livenessProbe:
          exec:
            command:
            - /sbin/health_check.sh 
            - livenessProbe
          initialDelaySeconds: {{ .Values.services.isvd.probes.initialDelaySeconds }}
          periodSeconds: {{ .Values.services.isvd.probes.periodSeconds }}

        readinessProbe:
          exec:
            command:
            - /sbin/health_check.sh
          initialDelaySeconds: {{ .Values.services.isvd.probes.initialDelaySeconds }}
          periodSeconds: {{ .Values.services.isvd.probes.periodSeconds }}

        startupProbe:
          exec:
            command:
            - /sbin/health_check.sh 
            - startupProbe
          initialDelaySeconds: {{ .Values.services.isvd.probes.initialDelaySeconds }}
          periodSeconds: {{ .Values.services.isvd.probes.periodSeconds }}

