apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: postgres
  template: 
    metadata:
      labels:
        app: postgres
        replicationRole: primary
    spec:
      {{ if not .Values.isOpenShift }}securityContext:
        runAsUser: {{ .Values.services.postgres.user }}
        fsGroup: {{ .Values.services.postgres.group }}{{end}}
      volumes:
      - name: data-volume 
        persistentVolumeClaim: 
          claimName: postgres-pvc
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: {{ .Values.services.postgres.sharedMemory | quote }}
      - name: certs
        configMap:
          name: isvgimdb
          defaultMode: 0640
      - name: init-script
        projected:
          sources:
          - configMap:
              name: isvgimdb
              items:
                - key: primary_init_script.sh
                  path: primary_init_script.sh
                  mode: 0755
      imagePullSecrets:
      - name: regcred
      containers:
      - name: postgres
        image: {{ .Values.images.postgres }}
        imagePullPolicy: IfNotPresent
        args:
        - -c
        - config_file=/tmp/isvgimdb/postgres.conf
        - -c
        - hba_file=/tmp/isvgimdb/pg_hba.conf
        ports:
        - containerPort: {{ .Values.services.postgres.ports.pg }}
        env:
        - name: PG_ISVGIM_USER
          valueFrom:
            secretKeyRef:
              name: pgcreds
              key: pguser
        - name: PG_ISVGIM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgcreds
              key: pgpass
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgcreds
              key: admpass
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pgcreds
              key: admuser
        - name: POSTGRES_DB
          value: {{ .Values.services.postgres.dbName }}
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: TZ
          value: ":{{ .Values.timezone }}"
        volumeMounts:
        - name: data-volume
          mountPath: /var/lib/postgresql/data
        - name: certs
          mountPath: /tmp/isvgimdb
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d/primary_init_script.sh
          subPath: primary_init_script.sh
        - name: dshm
          mountPath: /dev/shm
