apiVersion: apps/v1
kind: Deployment
metadata:
  name: isvdi
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: isvdi
  template: 
    metadata:
      labels:
        app: isvdi
    spec:
      {{ if not .Values.isOpenShift }}securityContext:
        fsGroup: 0{{end}}
      volumes:
      - name: config
        configMap:
          name: isvgimsdi
          defaultMode: 0640
      - name: init-script
        projected:
          sources:
          - configMap:
              name: isvgimsdi
              items:
                - key: setHostname.sh
                  path: setHostname.sh
                  mode: 0755
      - name: adapters
        persistentVolumeClaim:
          claimName: isvdi-pvc
      imagePullSecrets:
      - name: regcred
      containers:
      - name: isvdi
        image: {{ .Values.images.isvdi }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.services.isvdi.ports.api }}
          name: api
          protocol: TCP
        - containerPort: {{ .Values.services.isvdi.ports.object }}
          name: object
          protocol: TCP
        env:
        - name: YAML_CONFIG_FILE
          value: /tmp/isvgimsdi/isvdi_config.yaml
        - name: TZ
          value: ":{{ .Values.timezone }}"
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        volumeMounts:
        - name: config
          mountPath: /tmp/isvgimsdi
        - name: adapters
          mountPath: /opt/IBM/svgadapters
        - name: init-script
          mountPath: /home/isvdi/setHostname.sh
          subPath: setHostname.sh
