{
  "type": "record",
  "name": "assignment",
  "namespace": "com.ibm.security.csr.global.schema.data",
  "fields": [
    {
      "name": "id",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "name",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "assignmentDate",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "approverId",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "approverName",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "approverLevels",
      "type": [
        "null",
        "int"
      ],
      "default": null
    },
    {
      "name": "certificationApproverId",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "certificationApproverName",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "lastCertificationTime",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "workflowApproval",
      "type": [
        "null",
        "boolean"
      ],
      "default": null
    },
    {
      "name": "birthRight",
      "type": [
        "null",
        "boolean"
      ],
      "default": null
    },
    {
      "name": "creationTime",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "isLastActionAutomatic",
      "type": [
        "null",
        "boolean"
      ],
      "default": null
    }
  ]
}
