{
  "type":"record",
  "name":"CsrGlobalSchema",
  "namespace":"com.ibm.security.csr.global.schema",
  "fields":[
    {
      "name":"data",
      "type":[
        "null",
        {
          "type":"record",
          "name":"data",
          "fields":[
            {
              "name":"entId",
              "type":[
                "null",
                "string"
              ],
              "default": null
            },
            {
              "name":"evtDetails",
              "type":[
                "null",
                "string"
              ],
              "default": null
            },
            {
              "name":"tenant",
              "type":["null", com.ibm.security.csr.global.schema.data.tenant ],
              "default": null
            },
            {
              "name":"policy",
              "type":[ "null", com.ibm.security.csr.global.schema.data.policy],
              "default": null
            },
            {
              "name":"user",
              "type":["null", com.ibm.security.csr.global.schema.data.user],
              "default": null
            },
            {
              "name":"account",
              "type":["null", com.ibm.security.csr.global.schema.data.account ],
              "default": null
            },
            {
              "name":"application",
              "type":["null", com.ibm.security.csr.global.schema.data.application ],
              "default": null
            },
            {
              "name":"entitlement",
              "type":["null", com.ibm.security.csr.global.schema.data.entitlement ],
              "default": null
            },
            {
              "name":"assignment",
              "type":["null", com.ibm.security.csr.global.schema.data.assignment ],
              "default": null
            },
            {
              "name":"risk",
              "type":["null", com.ibm.security.csr.global.schema.data.risk ],
              "default": null
            }
          ]
        }
      ],
      "default": null
    },
    {
      "name":"evtCxt",
      "type":[
        "null",
        {
          "type":"record",
          "name":"evtCxt",
          "fields":[
            {
              "name":"action",
              "type":[
                "null",
                "string"
              ],
              "default": null
            },
            {
              "name":"astdEnt",
              "type":[
                {
                  "type":"array",
                  "items":[
                    "null",
                    "string"
                  ],
                  "default": null
                },
                "null"
              ]
            },
            {
              "name":"evtSubType",
              "type":[
                "null",
                "string"
              ],
              "default": null
            },
            {
              "name":"evtTs",
              "type":[
                "null",
                "long"
              ],
              "default": null
            },
            {
              "name":"evtType",
              "type":[
                "null",
                "string"
              ],
              "default": null
            },
            {
              "name":"srcEvtId",
              "type":[
                "null",
                "string"
              ],
              "default": null
            },
            {
              "name":"type",
              "type":[
                "null",
                "string"
              ],
              "default": null
            }
          ]
        }
      ],
      "default": null
    },
    {
      "name":"glbCxt",
      "type":[
        "null",
        {
          "type":"record",
          "name":"glbCxt",
          "fields":[
            {
              "name":"dcId",
              "type":[
                "null",
                "string"
              ],
              "default": null
            },
            {
              "name":"tntId",
              "type":[
                "null",
                "string"
              ],
              "default": null
            },
            {
              "name":"tntName",
              "type":[
                "null",
                "string"
              ],
              "default": null
            }
          ]
        }
      ],
      "default": null
    }
  ]
}
