{
  "type": "record",
  "name": "CsrGlobalSchema",
  "namespace": "com.ibm.security.csr.global.schema",
  "fields": [
    {
      "name": "data",
      "type": [
        "null",
        {
          "type": "record",
          "name": "data",
          "fields": [
            {
              "name": "entId",
              "type": [
                "null",
                "string"
              ]
            },
            {
              "name": "evtDetails",
              "type": [
                "null",
                "string"
              ]
            },
            {
              "name": "tenant",
              "type": [
                "null",
                {
                  "type": "record",
                  "name": "tenant",
                  "namespace": "com.ibm.security.csr.global.schema.data",
                  "fields": [
                    {
                      "name": "size",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "activeUsers",
                      "type": [
                        "null",
                        "long"
                      ]
                    }
                  ]
                }
              ]
            },
            {
              "name": "policy",
              "type": [
                "null",
                {
                  "type": "record",
                  "name": "policy",
                  "namespace": "com.ibm.security.csr.global.schema.data",
                  "fields": [
                    {
                      "name": "additionalRequiredAttributes",
                      "type": [
                        "null",
                        {
                          "type": "record",
                          "name": "additionalRequiredAttributes",
                          "fields": [
                            {
                              "name": "device",
                              "type": [
                                "null",
                                {
                                  "type": "array",
                                  "items": [
                                    "null",
                                    "string"
                                  ]
                                }
                              ]
                            },
                            {
                              "name": "user",
                              "type": [
                                "null",
                                {
                                  "type": "array",
                                  "items": [
                                    "null",
                                    "string"
                                  ]
                                }
                              ]
                            },
                            {
                              "name": "userDevice",
                              "type": [
                                "null",
                                {
                                  "type": "array",
                                  "items": [
                                    "null",
                                    "string"
                                  ]
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    },
                    {
                      "name": "aggrInterval",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "associatedEntities",
                      "type": [
                        "null",
                        {
                          "type": "array",
                          "items": [
                            "null",
                            "string"
                          ]
                        }
                      ]
                    },
                    {
                      "name": "countBasedAttributes",
                      "type": [
                        "null",
                        {
                          "type": "array",
                          "items": [
                            "null",
                            {
                              "type": "record",
                              "name": "countBasedAttributes",
                              "fields": [
                                {
                                  "name": "count",
                                  "type": [
                                    "null",
                                    "string"
                                  ]
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    },
                    {
                      "name": "counterChangePolicyAttribute",
                      "type": [
                        "null",
                        {
                          "type": "record",
                          "name": "counterChangePolicyAttribute",
                          "fields": [
                            {
                              "name": "counterKeyField",
                              "type": [
                                "null",
                                "string"
                              ]
                            },
                            {
                              "name": "counterValueField",
                              "type": [
                                "null",
                                "string"
                              ]
                            },
                            {
                              "name": "decrementalValue",
                              "type": [
                                "null",
                                "string"
                              ]
                            },
                            {
                              "name": "incrementalValue",
                              "type": [
                                "null",
                                "string"
                              ]
                            },
                            {
                              "name": "lookupField",
                              "type": [
                                "null",
                                "string"
                              ]
                            },
                            {
                              "name": "resetValue",
                              "type": [
                                "null",
                                "string"
                              ]
                            }
                          ]
                        }
                      ]
                    },
                    {
                      "name": "decay",
                      "type": [
                        "null",
                        "boolean"
                      ]
                    },
                    {
                      "name": "decayParameters",
                      "type": [
                        "null",
                        {
                          "type": "record",
                          "name": "decayParameters",
                          "fields": [
                            {
                              "name": "decayFactor",
                              "type": [
                                "null",
                                "double"
                              ]
                            },
                            {
                              "name": "freq",
                              "type": [
                                "null",
                                "string"
                              ]
                            },
                            {
                              "name": "fun",
                              "type": [
                                "null",
                                "string"
                              ]
                            },
                            {
                              "name": "startAfter",
                              "type": [
                                "null",
                                "long"
                              ]
                            }
                          ]
                        }
                      ]
                    },
                    {
                      "name": "description",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "editable",
                      "type": [
                        "null",
                        "boolean"
                      ]
                    },
                    {
                      "name": "id",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "isDeleted",
                      "type": [
                        "null",
                        "boolean"
                      ]
                    },
                    {
                      "name": "lastEnabledTime",
                      "type": [
                        "null",
                        "long"
                      ]
                    },
                    {
                      "name": "metadata",
                      "type": [
                        "null",
                        {
                          "type": "record",
                          "name": "metadata",
                          "fields": [
                            {
                              "name": "author",
                              "type": [
                                "null",
                                "string"
                              ]
                            },
                            {
                              "name": "createdDate",
                              "type": [
                                "null",
                                "string"
                              ]
                            },
                            {
                              "name": "lastUpdatedDate",
                              "type": [
                                "null",
                                "string"
                              ]
                            },
                            {
                              "name": "version",
                              "type": [
                                "null",
                                "string"
                              ]
                            }
                          ]
                        }
                      ]
                    },
                    {
                      "name": "name",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "tntId",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "parameters",
                      "type": [
                        "null",
                        {
                          "type": "array",
                          "items": [
                            "null",
                            {
                              "type": "record",
                              "name": "parameters",
                              "fields": [
                                {
                                  "name": "defaultValue",
                                  "type": [
                                    "null",
                                    "string"
                                  ]
                                },
                                {
                                  "name": "id",
                                  "type": [
                                    "null",
                                    "string"
                                  ]
                                },
                                {
                                  "name": "name",
                                  "type": [
                                    "null",
                                    "string"
                                  ]
                                },
                                {
                                  "name": "type",
                                  "type": [
                                    "null",
                                    "string"
                                  ]
                                },
                                {
                                  "name": "value",
                                  "type": [
                                    "null",
                                    "string"
                                  ]
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    },
                    {
                      "name": "policyCategory",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "policyClass",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "policyType",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "retentionPeriod",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "riskLevel",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "rollupEntities",
                      "type": [
                        "null",
                        {
                          "type": "array",
                          "items": [
                            "null",
                            "string"
                          ]
                        }
                      ]
                    },
                    {
                      "name": "remediationActions",
                      "type": [
                        "null",
                        {
                          "type": "array",
                          "items": [
                            "null",
                            "string"
                          ]
                        }
                      ]
                    },
                    {
                      "name": "rules",
                      "type": [
                        "null",
                        {
                          "type": "array",
                          "items": [
                            "null",
                            {
                              "type": "record",
                              "name": "rules",
                              "fields": [
                                {
                                  "name": "condition",
                                  "type": [
                                    "null",
                                    "string"
                                  ]
                                },
                                {
                                  "name": "description",
                                  "type": [
                                    "null",
                                    "string"
                                  ]
                                },
                                {
                                  "name": "enabled",
                                  "type": [
                                    "null",
                                    "boolean"
                                  ]
                                },
                                {
                                  "name": "id",
                                  "type": [
                                    "null",
                                    "string"
                                  ]
                                },
                                {
                                  "name": "name",
                                  "type": [
                                    "null",
                                    "string"
                                  ]
                                },
                                {
                                  "name": "severityBasedScore",
                                  "type": [
                                    "null",
                                    "long"
                                  ]
                                },
                                {
                                  "name": "severityType",
                                  "type": [
                                    "null",
                                    "string"
                                  ]
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    },
                    {
                      "name": "status",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "subscribedEvents",
                      "type": [
                        "null",
                        {
                          "type": "array",
                          "items": [
                            "null",
                            "string"
                          ]
                        }
                      ]
                    },
                    {
                      "name": "subscribedEventKey",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "timeoutDuration",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "tags",
                      "type": [
                        "null",
                        {
                          "type": "array",
                          "items": [
                            "null",
                            "string"
                          ]
                        }
                      ]
                    },
                    {
                      "name": "type",
                      "type": [
                        "null",
                        "string"
                      ]
                    }
                  ]
                }
              ]
            },
            {
              "name": "user",
              "type": [
                "null",
                {
                  "type": "record",
                  "name": "user",
                  "namespace": "com.ibm.security.csr.global.schema.data",
                  "fields": [
                    {
                      "name": "id",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "name",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "dn",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "familyName",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "givenName",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "status",
                      "type": [
                        "null",
                        "long"
                      ]
                    },
                    {
                      "name": "userCategory",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "pwdChangedTime",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "jobTitle",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "managerId",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "managerName",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "department",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "email",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "organizationalUnit",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "personDataType",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "isManager",
                      "type": [
                        "null",
                        "boolean"
                      ]
                    },
                    {
                      "name": "creationTime",
                      "type": [
                        "null",
                        "string"
                      ]
                    }
                  ]
                }
              ]
            },
            {
              "name": "account",
              "type": [
                "null",
                {
                  "type": "record",
                  "name": "account",
                  "namespace": "com.ibm.security.csr.global.schema.data",
                  "fields": [
                    {
                      "name": "id",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "name",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "dn",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "status",
                      "type": [
                        "null",
                        "long"
                      ]
                    },
                    {
                      "name": "lastPwdChangeDate",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "lastLogin",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "lastCertificationTime",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "applicationName",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "applicationId",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "complianceStatus",
                      "type": [
                        "null",
                        "long"
                      ]
                    },
                    {
                      "name": "creationTime",
                      "type": [
                        "null",
                        "string"
                      ]
                    }
                  ]
                }
              ]
            },
            {
              "name": "application",
              "type": [
                "null",
                {
                  "type": "record",
                  "name": "application",
                  "namespace": "com.ibm.security.csr.global.schema.data",
                  "fields": [
                    {
                      "name": "id",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "name",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "dn",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "description",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "ownerName",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "ownerId",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "creationTime",
                      "type": [
                        "null",
                        "string"
                      ]
                    }
                  ]
                }
              ]
            },
            {
              "name": "entitlement",
              "type": [
                "null",
                {
                  "type": "record",
                  "name": "entitlement",
                  "namespace": "com.ibm.security.csr.global.schema.data",
                  "fields": [
                    {
                      "name": "id",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "name",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "dn",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "type",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "subType",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "description",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "applicationId",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "applicationName",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "sensitive",
                      "type": [
                        "null",
                        "boolean"
                      ]
                    },
                    {
                      "name": "creationTime",
                      "type": [
                        "null",
                        "string"
                      ]
                    }
                  ]
                }
              ]
            },
            {
              "name": "assignment",
              "type": [
                "null",
                {
                  "type": "record",
                  "name": "assignment",
                  "namespace": "com.ibm.security.csr.global.schema.data",
                  "fields": [
                    {
                      "name": "id",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "name",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "assignmentDate",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "approverId",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "approverName",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "approverLevels",
                      "type": [
                        "null",
                        "int"
                      ]
                    },
                    {
                      "name": "certificationApproverId",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "certificationApproverName",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "lastCertificationTime",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "workflowApproval",
                      "type": [
                        "null",
                        "boolean"
                      ]
                    },
                    {
                      "name": "birthRight",
                      "type": [
                        "null",
                        "boolean"
                      ]
                    },
                    {
                      "name": "creationTime",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "isLastActionAutomatic",
                      "type": [
                        "null",
                        "boolean"
                      ]
                    }
                  ]
                }
              ]
            },
            {
              "name": "risk",
              "type": [
                "null",
                {
                  "type": "record",
                  "name": "risk",
                  "namespace": "com.ibm.security.csr.global.schema.data",
                  "fields": [
                    {
                      "name": "likelihood",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "level",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "trend",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "acceptRational",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "impact",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "name",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "description",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "id",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "type",
                      "type": [
                        "null",
                        "string"
                      ]
                    },
                    {
                      "name": "tolerance",
                      "type": [
                        "null",
                        "string"
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "name": "evtCxt",
      "type": [
        "null",
        {
          "type": "record",
          "name": "evtCxt",
          "fields": [
            {
              "name": "action",
              "type": [
                "null",
                "string"
              ]
            },
            {
              "name": "astdEnt",
              "type": [
                {
                  "type": "array",
                  "items": [
                    "null",
                    "string"
                  ]
                },
                "null"
              ]
            },
            {
              "name": "evtSubType",
              "type": [
                "null",
                "string"
              ]
            },
            {
              "name": "evtTs",
              "type": [
                "null",
                "long"
              ]
            },
            {
              "name": "evtType",
              "type": [
                "null",
                "string"
              ]
            },
            {
              "name": "srcEvtId",
              "type": [
                "null",
                "string"
              ]
            },
            {
              "name": "type",
              "type": [
                "null",
                "string"
              ]
            }
          ]
        }
      ]
    },
    {
      "name": "glbCxt",
      "type": [
        "null",
        {
          "type": "record",
          "name": "glbCxt",
          "fields": [
            {
              "name": "dcId",
              "type": [
                "null",
                "string"
              ]
            },
            {
              "name": "tntId",
              "type": [
                "null",
                "string"
              ]
            },
            {
              "name": "tntName",
              "type": [
                "null",
                "string"
              ]
            }
          ]
        }
      ]
    }
  ]
}
