{
  "type": "record",
  "name": "risk",
  "namespace": "com.ibm.security.csr.global.schema.data",
  "fields": [
    {
      "name": "likelihood",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "level",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "trend",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "acceptRational",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "impact",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "name",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "description",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "id",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "type",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "tolerance",
      "type": [
        "null",
        "string"
      ],
      "default": null
    }
  ]
}