{
   "type": "record",
   "name": "user",
   "namespace": "com.ibm.security.csr.global.schema.data",
   "fields": [
      {
         "name": "id",
         "type": [
            "null",
            "string"
         ],
         "default": null
      },
      {
         "name": "name",
         "type": [
            "null",
            "string"
         ],
         "default": null
      },
      {
         "name": "dn",
         "type": [
            "null",
            "string"
         ],
         "default": null
      },
      {
         "name": "familyName",
         "type": [
            "null",
            "string"
         ],
         "default": null
      },
      {
         "name": "givenName",
         "type": [
            "null",
            "string"
         ],
         "default": null
      },
      {
         "name": "status",
         "type": [
            "null",
            "long"
         ],
         "default": null
      },
      {
         "name": "userCategory",
         "type": [
            "null",
            "string"
         ],
         "default": null
      },
      {
         "name": "pwdChangedTime",
         "type": [
            "null",
            "string"
         ],
         "default": null
      },
      {
         "name": "jobTitle",
         "type": [
            "null",
            "string"
         ],
         "default": null
      },
      {
         "name": "managerId",
         "type": [
            "null",
            "string"
         ],
         "default": null
      },
      {
         "name": "managerName",
         "type": [
            "null",
            "string"
         ],
         "default": null
      },
      {
         "name": "department",
         "type": [
            "null",
            "string"
         ],
         "default": null
      },
      {
         "name": "email",
         "type": [
            "null",
            "string"
         ],
         "default": null
      },
      {
         "name": "organizationalUnit",
         "type": [
            "null",
            "string"
         ],
         "default": null
      },
      {
         "name": "personDataType",
         "type": [
            "null",
            "string"
         ],
         "default": null
      },
      {
         "name": "isManager",
         "type": [
            "null",
            "boolean"
         ],
         "default": null
      },
      {
         "name": "creationTime",
         "type": [
            "null",
            "string"
         ],
         "default": null
      }
   ]
}
