



spark.kubernetes.executor.podNamePrefix=spark-csr-executor
spark.sql.ui.retainedExecutions=100
spark.kubernetes.executor.deleteOnTermination=false
spark.executor.instances=1
spark.executor.memory=1500m
spark.driver.memory=1000m
spark.executor.cores=2
spark.driver.cores=1
spark.kubernetes.executor.request.cores=2
spark.kubernetes.driver.request.cores=1
spark.sql.shuffle.partitions=4
spark.task.maxFailures=100
spark.kubernetes.driverEnv.CONFIG_MANAGER_TYPE=PropertyFile
spark.kubernetes.driverEnv.STORAGE_TYPE=LOCAL
spark.kubernetes.driverEnv.INFRA_FILE_KEY=/tmp/store/config/infrastructureConfig.properties
spark.kubernetes.driverEnv.APP_CONFIG_KEY=/tmp/store/config/applicationConfig.properties
spark.kubernetes.driverEnv.RELATIONSHIP_METADATA_CONFIG_KEY=/tmp/store/config/relationshipMetadata.properties
spark.kubernetes.driverEnv.CHECKPOINT_BASE_DIR_LOCATION=/opt/spark/checkpoint
spark.kubernetes.driverEnv.SCHEMA_DIR=/tmp/store/schema
spark.kubernetes.driverEnv.SPARK_HOME=/opt/spark
spark.kubernetes.driver.secretKeyRef.MQ_PASS=riskcreds:mqpass
spark.kubernetes.driver.secretKeyRef.DB_PASS=riskcreds:dbpass
spark.kubernetes.driver.secretKeyRef.DB_USER=riskcreds:dbuser
spark.kubernetes.executor.secretKeyRef.MQ_PASS=riskcreds:mqpass
spark.kubernetes.executor.secretKeyRef.DB_PASS=riskcreds:dbpass
spark.kubernetes.executor.secretKeyRef.DB_USER=riskcreds:dbuser
spark.executorEnv.INFRA_FILE_KEY=/tmp/store/config/infrastructureConfig.properties
spark.executorEnv.APP_CONFIG_KEY=/tmp/store/config/applicationConfig.properties
spark.executorEnv.RELATIONSHIP_METADATA_CONFIG_KEY=/tmp/store/config/relationshipMetadata.properties
spark.executorEnv.CHECKPOINT_BASE_DIR_LOCATION=/opt/spark/checkpoint
spark.executorEnv.SCHEMA_DIR=/tmp/store/schema
spark.executorEnv.SPARK_HOME=/opt/spark
spark.kubernetes.driver.podTemplateFile=/tmp/store/templates/driver-pod-template.yaml
spark.kubernetes.executor.podTemplateFile=/tmp/store/templates/executor-pod-template.yaml
spark.sql.streaming.metricsEnabled=true
spark.metrics.staticSources.enabled=false
spark.metrics.executorMetricsSource.enabled=false
spark.metrics.appStatusSource.enabled=true
spark.network.crypto.enabled=true
spark.network.crypto.saslFallback=false
spark.network.crypto.keyLength=256
spark.network.crypto.keyFactoryAlgorithm=PBKDF2WithHmacSHA256
spark.network.crypto.config.secure.random.java.algorithm=PKCS11
spark.network.crypto.config.cipher.transformation=AES/CTR/PKCS5Padding
spark.kubernetes.driver.volumes.persistentVolumeClaim.datadir.options.claimName=riskengine-pvc
spark.kubernetes.driver.volumes.persistentVolumeClaim.datadir.mount.path=/opt/spark/checkpoint
spark.kubernetes.driver.volumes.persistentVolumeClaim.datadir.mount.readOnly=false
spark.kubernetes.executor.volumes.persistentVolumeClaim.datadir.options.claimName=riskengine-pvc
spark.kubernetes.executor.volumes.persistentVolumeClaim.datadir.mount.path=/opt/spark/checkpoint
spark.kubernetes.executor.volumes.persistentVolumeClaim.datadir.mount.readOnly=false
