---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: efs.csi.aws.com
spec:
  attachRequired: false
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  # Enter The file system ID That you created eg: fs-01563c43b86c85844
  fileSystemId: fs-xxxx
  directoryPerms: "777"
  uid: "1000"
  gid: "1000"
  # gidRangeStart: "1" 
  # gidRangeEnd: "2000" 
  basePath: "/dynamic_provisioning/pods" # optional
  # subPathPattern: "${.PVC.namespace}/${.PVC.name}" # optional
  # ensureUniqueDirectory: "true" # optional
  # reuseAccessPoint: "false" # optional
volumeBindingMode: WaitForFirstConsumer