



###########################
## This property file contains the configurations to manage common-streaming-application.
## The common streaming engine runs multiple streaming queries and those can be 
## configured using applicationConfig.properties
###########################


######
# This section contains configuration for different streaming queries
######
policyquery.name=PolicyQuery
policyquery.enabled=true
policyquery.enrich.enabled=true
policyquery.filter=evtCxt.type == 'policy'
policyquery.trigger.interval=10 seconds
policyquery.maxoffset.per.trigger=100
policyquery.storage.level=DISK_AND_MEMORY
policyquery.parallel.write.enabled=true
policyquery.bulk.delete.size=6
policyquery.deletion.filter=(evtCxt.action == 'delete' AND deletionFlag == true) OR (evtCxt.action == 'modify' AND deletionFlag == true AND data.policy.status == 'Inactive') OR (evtCxt.action == 'modify' AND deletionFlag == true AND data.policy.isDeleted == true)
policyquery.violation.deletion.flag=false

eventsdbsyncquery.name=EventsDbSyncQuery
eventsdbsyncquery.enabled=false
eventsdbsyncquery.trigger.interval=30 seconds
eventsdbsyncquery.maxoffset.per.trigger=10000
eventsdbsyncquery.storage.level=DISK_AND_MEMORY

entitysyncquery.name=EntitySyncQuery
entitysyncquery.enabled=false
entitysyncquery.es.sync.enabled=true
entitysyncquery.filter=evtCxt.type != 'tenant' AND evtCxt.type != 'policy'
entitysyncquery.trigger.interval=30 seconds
entitysyncquery.maxoffset.per.trigger=10000
entitysyncquery.storage.level=DISK_AND_MEMORY
entitysyncquery.parallel.write.enabled=true

dataquery.name=DataQuery
dataquery.enabled=true
dataquery.es.sync.enabled=true
dataquery.es.history.sync.enabled=true
dataquery.filter=evtCxt.type != 'TENANT_DELETION_MARKER' AND evtCxt.type != 'userDevice'
dataquery.trigger.interval=30 seconds
dataquery.maxoffset.per.trigger=10000
dataquery.storage.level=DISK_AND_MEMORY
dataquery.state.timestamp=procTs
dataquery.parallel.write.enabled=true
dataquery.count.aggregation.timestamp=evtTs

aggregationquery.name=AggregationQuery
aggregationquery.enabled=true
aggregationquery.filter=
aggregationquery.trigger.interval=30 seconds
aggregationquery.maxoffset.per.trigger=10000
aggregationquery.storage.level=DISK_AND_MEMORY
aggregationquery.parallel.write.enabled=true
aggregationquery.watermark=5 minutes

tenantquery.name=TenantQuery
tenantquery.enabled=false
tenantquery.filter=evtCxt.type == 'tenant'
tenantquery.trigger.interval=30 seconds
tenantquery.maxoffset.per.trigger=10000
tenantquery.storage.level=DISK

######
# This section contains configuration for overall application
######
cassandra.sync.enabled=false
cassandra.ttl.seconds=3600
cassandra.parallel.write.enabled=true

#state store config
rocksdb.statestore.enabled=true
statestore.processing.watermark=24 hour

query.trigger.interval=30 seconds
dataset.partitions=8

entity.archival.days=60

# This property used to provide OpenSearch indices list for which archival / clean up job should run.
#archival.index.list valid values are : ENTITY_SYNC:evtCxt.evtTs:60,DEVICE_HISTORY:modTime:60,USER_HISTORY:modTime:60,POLICY_VIOLATION_HISTORY:modTime:60,POLICY_HISTORY:metadata.lastUpdatedDate:60
archival.index.list=ACCOUNT_HISTORY:time:60,USER_HISTORY:time:60,POLICY_VIOLATION_HISTORY:modTime:60,APPLICATION_HISTORY:time:60

#Policy cache - Valid values are cassandra or deltatable
policy.cache.name=deltatable

#Entity aggregation history days
entity.aggregation.history.days=60

#supportedEntities
supported.entities=user,account,application,entitlement,assignment,risk

#supportedRelationship
supported.relations=


#violation enrichment, id,name added by default
violation.user.info.additionalfields=email
violation.device.info.additionalfields=managedStatus,platformName,appSecurityPosture

# Properties for elastic search bulk read configuration
es.read.bulkSize=1000
es.read.default.partitions=2

policyviolation.es.array.fields.list=associatedEntities,rollupEntities,tags

query.debugFlag=true
query.restart.count=10
query.restart.sleep=30000

es.output.validation=true

kryo.serialization.enabled=false

policy.es.array.fields=subscribedEvents,associatedEntities,rollupEntities,countBasedAttributes,tags,additionalRequiredAttributes.*,rules,parameters

policy.es.read.field.exclude=version,createdDate,lastUpdatedDate,metadata.createdDate,metadata.lastUpdatedDate

es.upsert.feature.flag=false

dataquery.violation.script.json.fields=usrInfo,eventInfo,devInfo,ruleInfo,policyInfo

# Enable this flag to log srcEvtId of events received from events egress topic
event.logging.enabled=true
# batch job
batch.job.storage.level=DISK
decay.batch.job.enabled=true
org.level.aggregation.batch.job.enabled=true
cleanup.batch.job.enabled=true
driver.exit.status.code=1
decay.multiTenant.batch.job.enabled=true
decay.multiTenant.batch.job.cntAggregationQuery.tntThreshold = 5
decay.multiTenant.batch.job.tntCount.threshold=10
decay.multiTenant.batch.job.violationCount.threshold=1000
decay.multiTenant.batch.job.retryCount=3
decay.multiTenant.batch.job.retrySleep.ms=10000

device.cassandra.write.skip.fields=appSecurityPosture

org.level.aggregation.batch.job.update.old.avg.score=true

streaming.datasource=postgres
streaming.eventssource=ibmmq
