{
  "type": "record",
  "name": "account",
  "namespace": "com.ibm.security.csr.global.schema.data",
  "fields": [
    {
      "name": "id",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "name",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "dn",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "status",
      "type": [
        "null",
        "long"
      ],
      "default": null
    },
    {
      "name": "lastPwdChangeDate",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "lastLogin",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "lastCertificationTime",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "applicationName",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "applicationId",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "complianceStatus",
      "type": [
        "null",
        "long"
      ],
      "default": null
    },
    {
      "name": "creationTime",
      "type": [
        "null",
        "string"
      ],
      "default": null
    }
  ]
}