{
  "type": "record",
  "name": "application",
  "namespace": "com.ibm.security.csr.global.schema.data",
  "fields": [
    {
      "name": "id",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "name",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "dn",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "description",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "ownerName",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "ownerId",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "creationTime",
      "type": [
        "null",
        "string"
      ],
      "default": null
    }
  ]
}