{
  "type": "record",
  "name": "entitlement",
  "namespace": "com.ibm.security.csr.global.schema.data",
  "fields": [
    {
      "name": "id",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "name",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "dn",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "type",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "subType",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "description",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "applicationId",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "applicationName",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "sensitive",
      "type": [
        "null",
        "boolean"
      ],
      "default": null
    },
    {
      "name": "creationTime",
      "type": [
        "null",
        "string"
      ],
      "default": null
    }
  ]
}
