apiVersion: v1
kind: Pod
spec:
  volumes:
    - name: store
      configMap:
        name: ivigrisk
    - name: config
      configMap:
        name: isvgimconfig
  containers:
    - name: spark-kubernetes-executor # This will be interpreted as executor Spark main container
      command: [ "/bin/sh", "-c", "tar zxf /tmp/storecfg/risk.tgz -C /tmp; /tmp/store/setup.sh; /opt/entrypoint.sh executor" ]
      volumeMounts:
        - name: store
          mountPath: /tmp/storecfg
        - name: config
          mountPath: /tmp/isvgimcfg
