apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: replica-1-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: {{ .Values.storage.className }}
  resources:
    requests:
      storage: {{ .Values.storage.volumes.isvd }}
