apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: isvdi-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes: [ "{{ .Values.storage.mode }}" ]
  storageClassName: {{ .Values.storage.className }}
  resources:
    requests:
      storage: {{ .Values.storage.volumes.isvdi }}
