apiVersion: v1
kind: Service
metadata:
  name: isvgim
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
    - name: https
      port: {{ .Values.services.isvgim.ports.https }}
      protocol: TCP
      targetPort: {{ .Values.services.isvgim.ports.https }}
      nodePort: {{ .Values.services.isvgim.ports.node }}
    - name: iiop
      port: {{ .Values.services.isvgim.ports.iiop }}
      protocol: TCP
      targetPort: {{ .Values.services.isvgim.ports.iiop }}
      nodePort: {{ .Values.services.isvgim.ports.iiop }}
    - name: iiops
      port: {{ .Values.services.isvgim.ports.iiops }}
      protocol: TCP
      targetPort: {{ .Values.services.isvgim.ports.iiops }}
      nodePort: {{ .Values.services.isvgim.ports.iiops }}
  selector:
    app: isvgim
