apiVersion: v1
kind: Service
metadata:
  name: isvd-cluster
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: isvd-proxy
  ports:
    - name: isvd-proxy-ldaps
      protocol: TCP
      port: {{ .Values.services.isvdproxy.ports.ldapsproxy }}
