apiVersion: v1
kind: Service
metadata:
  name: postgres-external
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.services.postgres.ports.pg }}
    name: postgres-pg
    protocol: TCP
    nodePort: {{ .Values.services.postgres.ports.node }}
  selector:
    app: postgres
    replicationRole: primary
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-external-standby
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.services.postgres.ports.pg }}
    name: postgres-standby
    protocol: TCP
    nodePort: {{ add .Values.services.postgres.ports.node 1 }}
  selector:
    app: postgres
    replicationRole: replica
  type: NodePort

