apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqshare
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: mqshare
  template: 
    metadata:
      labels:
        app: mqshare
      annotations:
        productName: "IBM MQ"
        productId: "c661609261d5471fb4ff8970a36bccea"
        productMetric: "PROCESSOR_VALUE_UNIT"
        productChargedContainers: "All"
    spec:
      {{ if not .Values.isOpenShift }}securityContext:
        fsGroup: {{ .Values.services.mqshare.group }}{{end}}
      volumes:
      - name: mqconfig
        configMap:
          name: mqcfg
      - name: datadir
        persistentVolumeClaim:
          claimName: mqshare-pvc
      - name: mqconfigtls
        configMap:
          name: tlsmqcfg

      imagePullSecrets:
      - name: regcred

      containers:
      - name: mqshare
        image: {{ .Values.images.mq }}
        imagePullPolicy: IfNotPresent
        ports:
        - name: mq
          containerPort: {{ .Values.services.mqshare.ports.mq }}
          protocol: TCP
        - name: console
          containerPort: {{ .Values.services.mqshare.ports.console }}
          protocol: TCP
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: LICENSE
          value: "accept"
        - name: MQ_QMGR_NAME
          value: {{ .Values.services.mqshare.qmgr | quote }}
        - name: MQ_APP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mqcreds
              key: mqshare
        - name: MQ_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mqcreds
              key: mqadmin
        - name: TZ
          value: ":{{ .Values.timezone }}"
        - name: MQ_ENABLE_FIPS
          value: {{ .Values.fips | quote }}
        readinessProbe:
          exec:
            command:
            - /usr/local/bin/chkmqready
          failureThreshold: {{ .Values.services.mqshare.probes.failureThreshold }}
          initialDelaySeconds: {{ .Values.services.mqshare.probes.initialDelaySeconds }}
          periodSeconds: {{ .Values.services.mqshare.probes.periodSeconds }}
          successThreshold: {{ .Values.services.mqshare.probes.successThreshold }}
          timeoutSeconds: {{ .Values.services.mqshare.probes.timeoutSeconds }}
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/chkmqhealthy
          failureThreshold: {{ .Values.services.mqshare.probes.failureThreshold }}
          initialDelaySeconds: {{ .Values.services.mqshare.probes.initialDelaySeconds }}
          periodSeconds: {{ .Values.services.mqshare.probes.periodSeconds }}
          successThreshold: {{ .Values.services.mqshare.probes.successThreshold }}
          timeoutSeconds: {{ .Values.services.mqshare.probes.timeoutSeconds }}
        startupProbe:
          exec:
            command:
            - /usr/local/bin/chkmqstarted
          failureThreshold: {{ .Values.services.mqshare.probes.failureThreshold }}
          initialDelaySeconds: {{ .Values.services.mqshare.probes.initialDelaySeconds }}
          periodSeconds: {{ .Values.services.mqshare.probes.periodSeconds }}
          successThreshold: {{ .Values.services.mqshare.probes.successThreshold }}
          timeoutSeconds: {{ .Values.services.mqshare.probes.timeoutSeconds }}
        volumeMounts:
        - name: datadir
          mountPath: /mnt/mqm               
        - name: mqconfig
          mountPath: /etc/mqm/ISVGContainerQMgr-shared.mqsc
          subPath: ISVGContainerQMgr-shared.mqsc
        - name: mqconfig
          mountPath: /etc/mqm/isvgqm.ini
          subPath: isvgqm.ini
        - name: mqconfigtls
          mountPath: /etc/mqm/pki/keys/mykey

