apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app: isvgim
  name: isvgim
  namespace: {{ .Values.namespace }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: isvgim
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: isvgim
  namespace: {{ .Values.namespace }}
spec:
  podManagementPolicy: OrderedReady
  replicas: {{ .Values.services.isvgim.config.replicas }}
  revisionHistoryLimit: 1
  minReadySeconds: {{ .Values.services.isvgim.config.minReadySeconds }}
  selector:
    matchLabels:
      app: isvgim
  serviceName: "mq-headless"
  template:
    metadata:
      labels:
        app: isvgim
      annotations:
        productName: "IBM Verify Identity Governance Lifecycle"
        productId: "1fcf57ba04ee4a779a860a8d1fac675e"
        productMetric: "{{ .Values.licenseType }}_VALUE_UNIT"
        productChargedContainers: "All"
    spec:
      serviceAccountName: hazelcast-sa
      imagePullSecrets:
      - name: regcred
      containers:
      - name: isvgim
        image: {{ .Values.images.isvgim }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.services.isvgim.ports.https }}
          name: https
          protocol: TCP
        - containerPort: {{ .Values.services.isvgim.ports.iiop }}
          name: iiop
          protocol: TCP
        - containerPort: {{ .Values.services.isvgim.ports.hazelcast }}
          name: hazelcast-port
          protocol: TCP
        env:
        - name: ADMIN_UI_TIMEOUT
          value: {{ .Values.services.isvgim.config.adminUITimeoutSeconds | quote }}
        - name: LIBERTY_LTPA_TIMEOUT
          value: {{ .Values.services.isvgim.config.libertyLtpaTimeout | quote }}
        - name: ISC_UI_TIMEOUT
          value: {{ .Values.services.isvgim.config.iscUITimeoutSeconds | quote }}
        - name: DEBUG_INIT
          value: {{ .Values.services.isvgim.config.debugInitScripts | quote }}
        - name: HEALTHCHECK_HEARTBEAT
          value: {{ .Values.services.isvgim.config.healthcheckHeartbeatInSecs | quote }}
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: LIBERTY_LOG_MAX_FILE_SIZE
          value: {{ .Values.services.isvgim.config.libertyLogMaxFileSize | quote }}
        - name: LIBERTY_LOG_MAX_FILES
          value: {{ .Values.services.isvgim.config.libertyLogMaxFiles | quote }}
        - name: LIBERTY_CONSOLE_LOG_LEVEL
          value: {{ .Values.services.isvgim.config.libertyConsoleLogLevel | quote }}
        - name: MQ_LOCAL_MQ_PORT
          value: {{ .Values.services.mqlocal.ports.mq | quote }}
        - name: MQ_USER_LOCAL
          value: {{ .Values.services.mqlocal.user | quote }}
        - name: ORB_IIOP_PORT
          value: {{ .Values.services.isvgim.ports.iiop | quote }}
        - name: ORB_IIOPS_PORT
          value: {{ .Values.services.isvgim.ports.iiops | quote }}
        - name: LIBERTY_HTTPS_PORT
          value: {{ .Values.services.isvgim.ports.https | quote }}
        - name: LIBERTY_VERIFY_HOSTNAME
          value: {{ .Values.services.isvgim.config.libertyVerifyHostname | quote }}
        - name: HAZELCAST_PORT
          value: {{ .Values.services.isvgim.ports.hazelcast | quote }}
        {{ if .Values.services.isvgim.config.libertyTrustLocalHosts }}- name: LIBERTY_TRUST_SDI
          value: "*.{{ .Values.namespace }}.pod.cluster.local"{{end}}
        - name: LIBERTY_TRANSACTION_TIMEOUT
          value: {{ .Values.services.isvgim.config.libertyTransactionTimeout | quote }}
        - name: IM_LICENSE_TYPE
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['productMetric']
        - name: IM_LICENSE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['productId']
        - name: IM_LICENSE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['productName']
        - name: IM_LICENSE_TOKEN
          valueFrom:
            secretKeyRef:
              name: ibm-licensing-upload-token
              key: token-upload
              optional: true
        - name: IM_LICENSE_SERVER
          valueFrom:
            configMapKeyRef:
              name: ibm-licensing-upload-config
              key: url
              optional: true
        - name: MQ_PASS_LOCAL
          valueFrom:
            secretKeyRef:
              name: mqcreds
              key: mqlocal
        - name: MQ_SHARED_MQ_HOST
          value: {{ .Values.services.mqshare.hostname | quote }}
        - name: MQ_USER_SHARED
          value: {{ .Values.services.mqshare.user | quote }}
        - name: MQ_PASS_SHARED
          valueFrom:
            secretKeyRef:
              name: mqcreds
              key: mqshare
        - name: OIDC_ADMINCONSOLE_USER
          valueFrom:
            secretKeyRef:
              name: oidccreds
              key: adminConsoleuser
        - name: OIDC_ADMINCONSOLE_SECRET
          valueFrom:
            secretKeyRef:
              name: oidccreds
              key: adminConsolesecret
        - name: OIDC_ISC_USER
          valueFrom:
            secretKeyRef:
              name: oidccreds
              key: iscuser
        - name: OIDC_ISC_SECRET
          valueFrom:
            secretKeyRef:
              name: oidccreds
              key: iscsecret
        - name: OIDC_REST_USER
          valueFrom:
            secretKeyRef:
              name: oidccreds
              key: restuser
        - name: OIDC_REST_SECRET
          valueFrom:
            secretKeyRef:
              name: oidccreds
              key: restsecret
        - name: TZ
          value: ":{{ .Values.timezone }}"
        volumeMounts:
        - mountPath: /tmp/isvgimks
          name: keystore
        - mountPath: /tmp/isvgimdata
          name: properties
        - mountPath: /tmp/spark
          name: spark
        - mountPath: /tmp/isvgimcfg
          name: config
        - name: ilmtcert
          mountPath: /work/licenseServerCA.pem
          subPath: crt.pem
        - name: logs
          mountPath: /logs
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: {{ .Values.services.isvgim.ports.https }}
            scheme: HTTPS
          failureThreshold: {{ .Values.services.isvgim.probes.failureThreshold }}
          initialDelaySeconds: {{ .Values.services.isvgim.probes.initialDelaySeconds }}
          periodSeconds: {{ .Values.services.isvgim.probes.periodSeconds }}
          successThreshold: {{ .Values.services.isvgim.probes.successThreshold }}
          timeoutSeconds: {{ .Values.services.isvgim.probes.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: {{ .Values.services.isvgim.ports.https }}
            scheme: HTTPS
          failureThreshold: {{ .Values.services.isvgim.probes.failureThreshold }}
          initialDelaySeconds: {{ .Values.services.isvgim.probes.initialDelaySeconds }}
          periodSeconds: {{ .Values.services.isvgim.probes.periodSeconds }}
          successThreshold: {{ .Values.services.isvgim.probes.successThreshold }}
          timeoutSeconds: {{ .Values.services.isvgim.probes.timeoutSeconds }}
        startupProbe:
          httpGet:
            path: /healthcheck
            port: {{ .Values.services.isvgim.ports.https }}
            scheme: HTTPS
          failureThreshold: {{ .Values.services.isvgim.probes.failureThreshold }}
          initialDelaySeconds: {{ add .Values.services.isvgim.probes.initialDelaySeconds 30 }}
          periodSeconds: {{ add .Values.services.isvgim.probes.periodSeconds 15 }}
          successThreshold: {{ .Values.services.isvgim.probes.successThreshold }}
          timeoutSeconds: {{ .Values.services.isvgim.probes.timeoutSeconds }}
      - name: mqlocal
        image: {{ .Values.images.mq }}
        imagePullPolicy: IfNotPresent
        ports:
        - name: mq
          containerPort: {{ .Values.services.mqlocal.ports.mq }}
          protocol: TCP
        - name: console
          containerPort: {{ .Values.services.mqlocal.ports.console }}
          protocol: TCP
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: LICENSE
          value: "accept"
        - name: MQ_QMGR_NAME
          value: {{ .Values.services.mqlocal.qmgr }}
        - name: MQ_APP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mqcreds
              key: mqlocal
        - name: MQ_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mqcreds
              key: mqadmin
        - name: TZ
          value: ":{{ .Values.timezone }}"
        - name: MQ_ENABLE_FIPS
          value: {{ .Values.fips | quote }}
        readinessProbe:
          exec:
            command:
            - /usr/local/bin/chkmqready
          failureThreshold: {{ .Values.services.mqlocal.probes.failureThreshold }}
          initialDelaySeconds: {{ .Values.services.mqlocal.probes.initialDelaySeconds }}
          periodSeconds: {{ .Values.services.mqlocal.probes.periodSeconds }}
          successThreshold: {{ .Values.services.mqlocal.probes.successThreshold }}
          timeoutSeconds: {{ .Values.services.mqlocal.probes.timeoutSeconds }}
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/chkmqhealthy
          failureThreshold: {{ .Values.services.mqlocal.probes.failureThreshold }}
          initialDelaySeconds: {{ .Values.services.mqlocal.probes.initialDelaySeconds }}
          periodSeconds: {{ .Values.services.mqlocal.probes.periodSeconds }}
          successThreshold: {{ .Values.services.mqlocal.probes.successThreshold }}
          timeoutSeconds: {{ .Values.services.mqlocal.probes.timeoutSeconds }}
        startupProbe:
          exec:
            command:
            - /usr/local/bin/chkmqstarted
          failureThreshold: {{ .Values.services.mqlocal.probes.failureThreshold }}
          initialDelaySeconds: {{ .Values.services.mqlocal.probes.initialDelaySeconds }}
          periodSeconds: {{ .Values.services.mqlocal.probes.periodSeconds }}
          successThreshold: {{ .Values.services.mqlocal.probes.successThreshold }}
          timeoutSeconds: {{ .Values.services.mqlocal.probes.timeoutSeconds }}
        volumeMounts:
        - mountPath: /mnt/mqm
          name: datadir               
        - mountPath: /etc/mqm/ISVGContainerQMgr.mqsc
          subPath: ISVGContainerQMgr.mqsc
          name: mqconfig
        - mountPath: /etc/mqm/web/installations/Installation1/servers/mqweb/mqwebuser.xml
          subPath: mqwebuser.xml
          name: mqconfig
        - name: mqconfig
          mountPath: /etc/mqm/isvgqm.ini
          subPath: isvgqm.ini
        - name: mqconfigtls
          mountPath: /etc/mqm/pki/keys/mykey
      - name: logs-liberty
        image: {{ .Values.images.isvgim }}
        imagePullPolicy: IfNotPresent
        args: [ "/bin/sh", "-c", "tail -n+1 -F /logs/console.log" ]
        volumeMounts:
        - name: logs
          mountPath: /logs
      - name: logs-im
        image: {{ .Values.images.isvgim }}
        imagePullPolicy: IfNotPresent
        args: [ "/bin/sh", "-c", "tail -n+1 -F /logs/ivig_console.log" ]
        volumeMounts:
        - name: logs
          mountPath: /logs
      hostAliases:
      - ip: 0.0.0.0
        hostnames:
        - isvgim.local
      restartPolicy: Always
      {{ if not .Values.isOpenShift }}securityContext:
        fsGroup: {{ .Values.services.mqlocal.group }}{{end}}
      volumes:
      - name: mqconfig
        configMap:
          name: mqcfg
      - name: keystore
        configMap:
          name: isvgimks
      - name: properties
        configMap:
          name: isvgimdata
      - name: spark
        configMap:
          name: ivigrisk
          optional: true
      - name: config
        configMap:
          name: isvgimconfig
      - name: ilmtcert
        configMap:
          name: ibm-licensing-upload-config
          optional: true
      - name: logs
        emptyDir: {}
      - name: mqconfigtls
        configMap:
          name: tlsmqcfg
  volumeClaimTemplates:
  - metadata:
      name: datadir
      namespace: {{ .Values.namespace }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.storage.volumes.mqlocal }}
      storageClassName: {{ .Values.storage.className }}

