apiVersion: batch/v1
kind: Job

metadata:
  name: isvd-seed
  namespace: {{ .Values.namespace }}
  labels:
    app: isvd-seed

spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 1

  template: 

    spec:
      {{ if not .Values.isOpenShift }}securityContext:
        runAsUser: {{ .Values.services.isvd.user }}
        fsGroup: {{ .Values.services.isvd.group }}{{end}}

      # We use a volume to store the configuration for the 
      # environment.
      volumes:
      - name: config-volume
        configMap:
          name: isvgimldap
      - name: principal-volume
        persistentVolumeClaim:
          claimName: replica-1-pvc
      - name: data-volume 
        persistentVolumeClaim: 
          claimName: replica-2-pvc

      imagePullSecrets:
      - name: regcred

      containers:
      - name: isvd-seed

        # The fully qualified name of the image.
        image: {{ .Values.images.isvdseed }}
        imagePullPolicy: IfNotPresent

        # Environment definition.
        env:
        - name: YAML_CONFIG_FILE
          value: /var/isvd/config/seed_config.yaml

        # The configuration volume.
        volumeMounts:
        - name: config-volume
          mountPath: /var/isvd/config
        - name: data-volume
          mountPath: /var/isvd/data
        - name: principal-volume
          mountPath: /var/isvd/source

      restartPolicy: Never
