apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}

spec:
  replicas: 3
  image: {{ .Values.images.postgres }}
  database:
    size: {{ .Values.storage.volumes.postgres }}
    storageClassName: {{ .Values.storage.className }}
    volumeMount: /var/lib/postgresql/data
  customConfig: isvgimdb
  {{ if not .Values.isOpenShift }}securityContext:
    runAsUser: {{ .Values.services.postgres.user }}
    fsGroup: {{ .Values.services.postgres.group }}{{end}}
  volume:
    volumes:
    - name: certs
      configMap:
        name: isvgimdb
        defaultMode: 0640
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: {{ .Values.services.postgres.sharedMemory | quote }} 
    volumeMounts:
    - name: certs
      mountPath: /tmp/isvgimdb
    - name: dshm
      mountPath: /dev/shm

  env:
    - name: PG_ISVGIM_PASSWORD
      valueFrom:
        secretKeyRef:
          name: pgcreds
          key: pgpass
    - name: POSTGRES_REPLICATION_PASSWORD
      valueFrom:
        secretKeyRef:
          name: pgcreds
          key: admpass
    - name: PG_ISVGIM_USER
      valueFrom:
        secretKeyRef:
          name: pgcreds
          key: pguser
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: pgcreds
          key: admpass
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: pgcreds
          key: admuser
    - name: POSTGRES_DB
      value: {{ .Values.services.postgres.dbName }}
    - name: PGDATA
      value: /var/lib/postgresql/data/pgdata
    - name: TZ
      value: ":{{ .Values.timezone }}"
