apiVersion: batch/v1
kind: Job

metadata:
  name: risk-start
  namespace: {{ .Values.namespace }}
  labels:
    app: risk-start

spec:
  ttlSecondsAfterFinished: 30
  backoffLimit: 3
  completions: 3
  template: 
    spec:
      {{ if not .Values.isOpenShift }}securityContext:
        runAsUser: {{ .Values.services.riskengine.user }}
        fsGroup: 0{{end}}
      serviceAccountName: {{ .Values.services.riskengine.serviceAccount }}
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: store
        configMap:
          name: ivigrisk
          defaultMode: 0777
      - name: config
        configMap:
          name: isvgimconfig

      containers:
      - name: csr-job
        image: {{ .Values.images.riskengine }}
        imagePullPolicy: IfNotPresent
        command:
          - "/bin/sh"
          - "-c"
          - >
            tar zxf /tmp/storecfg/risk.tgz -C /tmp;
            /tmp/store/setup.sh;
            sleep 10;
            sh /opt/spark/bin/spark-submit
            --master k8s://{{ .Values.clusterUrl }}
            --deploy-mode cluster
            --name spark-csr
            --conf spark.authenticate=true
            --conf spark.driver.extraJavaOptions="-Dlog4j.configuration=file:/tmp/store/config/log4j.properties -XX:+UseCompressedOops -XX:+UseG1GC -Djava.util.logging.config.file=/tmp/store/config/logging.properties -Dcom.ibm.jsse2.usefipsprovider=true -Dcom.ibm.jsse2.usefipsProviderName=com.ibm.crypto.fips.provider.IBMJCEFIPS"
            --conf spark.executor.extraJavaOptions="-Dlog4j.configuration=file:/tmp/store/config/log4j.properties -XX:+UseG1GC -XX:+UseCompressedOops -Djava.util.logging.config.file=/tmp/store/config/logging.properties -Dcom.ibm.jsse2.usefipsprovider=true -Dcom.ibm.jsse2.usefipsProviderName=com.ibm.crypto.fips.provider.IBMJCEFIPS"
            --conf spark.kubernetes.container.image={{ .Values.images.riskengine }}
            --conf spark.kubernetes.container.image.pullPolicy=IfNotPresent
            --conf spark.kubernetes.container.image.pullSecrets=regcred
            --conf spark.kubernetes.authenticate.driver.serviceAccountName={{ .Values.services.riskengine.serviceAccount }}
            --conf spark.kubernetes.namespace={{ .Values.namespace }}
            --conf spark.kubernetes.driver.label.job=streaming-csr
            --conf spark.kubernetes.driver.label.pod=spark-csr-pod
            --conf spark.kubernetes.executor.label.pod=streaming-csr-executor
            --conf spark.kubernetes.memoryOverheadFactor=0.5
            --conf spark.serializer=org.apache.spark.serializer.KryoSerializer
            --conf spark.cassandra.output.ignoreNulls=true
            --conf spark.sql.streaming.noDataMicroBatches.enabled=false
            --conf spark.memory.storageFraction=0.3
            --conf spark.sql.catalog.spark_catalog="org.apache.spark.sql.delta.catalog.DeltaCatalog"
            --conf spark.sql.streaming.minBatchesToRetain=30
            --conf spark.kubernetes.file.upload.path=/opt/spark/jars
            --properties-file /tmp/store/config/mainJob.properties
            --class com.ibm.security.csr.streaming.core.job.CSRStreamingJob
            local:///opt/spark/jars/com.ibm.security.csr.streaming-core.streaming-app_1.0.jar

        volumeMounts:
        - name: store
          mountPath: /tmp/storecfg
        - name: config
          mountPath: /tmp/isvgimcfg

        env:
        - name: PATH
          value: "/usr/bin:/usr/sbin:/opt/spark/sbin:/opt/spark/bin:/opt/ibm/java/jre/bin"
        - name: TZ
          value: ":{{ .Values.timezone }}"
      restartPolicy: Never
