apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-node1
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.storage.volumes.isvgimcustom }}
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /tmp/customizations
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1
